spring:
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false #Spring Boot 3.x not support
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_versioned_data: true
          batch_size: 100
  datasource:
    url: jdbc:h2:mem:dayone;DB_CLOSE_DELAY=-1
    username: sa
    password:
  redis:
    host: localhost
    port: 6379
  jwt:
    secret: "aaaaagaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" # >= 256bits
scheduler.scrap:
  yahoo: "0 0 0 * * *"