spring:
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false #Spring Boot 3.x not support
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:dayone;DB_CLOSE_DELAY=-1
    username: sa
    password:
scheduler.scrap:
  yahoo: "0 0 0 * * *"